steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor-protoform/blackduck-operator:$BRANCH_NAME', './']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor-protoform/blackduck-operator:$BRANCH_NAME']


