steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', './output/operator', './cmd/operator/']
  env:
  - 'PROJECT_ROOT=github.com/blackducksoftware/perceptor-protoform'
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'
  - 'GOARCH=amd64'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', "-t", 'gcr.io/$PROJECT_ID/blackducksoftware/opssight/blackduck-operator-ui:$BRANCH_NAME', "./cmd/operator-ui"]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blackducksoftware/opssight/blackduck-operator-ui:$BRANCH_NAME']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blackducksoftware/opssight/blackduck-operator:$BRANCH_NAME']


