steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', './cmd/protoform-installer/protoform-installer', './cmd/protoform-installer/installer.go']
  env:
  - 'PROJECT_ROOT=github.com/blackducksoftware/perceptor-protoform'
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'
  - 'GOARCH=amd64'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor-protoform:$BRANCH_NAME', './cmd/protoform-installer']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blackducksoftware/perceptor-protoform:$BRANCH_NAME']

- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', './cmd/hub-federator/hub-federator', './cmd/hub-federator/installer.go']
  env:
  - 'PROJECT_ROOT=github.com/blackducksoftware/perceptor-protoform'
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'
  - 'GOARCH=amd64'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blackducksoftware/hub-federator:$BRANCH_NAME', './cmd/hub-federator']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blackducksoftware/hub-federator:$BRANCH_NAME']

- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', './cmd/protoform-bootstrapper/protoform-bootstrapper', './cmd/protoform-bootstrapper/bootstrapper.go']
  env:
  - 'PROJECT_ROOT=github.com/blackducksoftware/perceptor-protoform'
  - 'CGO_ENABLED=0'
  - 'GOOS=linux'
  - 'GOARCH=amd64'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blackducksoftware/protoform-bootstrapper:$BRANCH_NAME', './cmd/protoform-bootstrapper']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blackducksoftware/protoform-bootstrapper:$BRANCH_NAME']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    curl -d "" -X POST http://ec2-54-205-198-237.compute-1.amazonaws.com:8081/webhook-perceptor/$REPO_NAME || echo "Success"
