steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o',' blackduckctl', './cmd/blackduckctl']
  env: ['PROJECT_ROOT=cmd/blackduckctl']
artifacts:
  objects:
    location: 'gs://saas-hub-stg/perceptor/blackduckctl'
    paths: ['./cmd/blackduckctl/blackduckctl']