apiVersion: synopsys.com/v1
kind: OpsSight
metadata:
  clusterName: ""
  name: opssight-test1
spec:
  namespace: opssight-test1
  # CONTAINER CONFIGS
  # These are sed replaced into the config maps for the containers.
  perceptorPort: 3001
  perceiverPort: 3002
  scannerPort: 3003
  imageFacadePort: 3004
  skyfirePort: 3005
  internalRegistries: []
  annotationIntervalSeconds: 30
  dumpIntervalMinutes: 30
  hubHost: webserver.pvc-test.svc
  hubUser: sysadmin
  hubPort: 443
  hubUserPassword: blackduck
  hubClientTimeoutPerceptorMilliseconds: 5000
  hubClientTimeoutScannerSeconds: 30
  concurrentScanLimit: 7
  defaultVersion: 2.0.3

  # CONTAINER PULL CONFIG
  # These are for defining docker registry and image location and versions
  registry: docker.io
  imagePath: blackducksoftware

  perceptorImageName: opssight-core
  scannerImageName: opssight-scanner
  podPerceiverImageName: opssight-pod-processor
  imagePerceiverImageName: opssight-image-processor
  imageFacadeImageName: opssight-image-getter
  skyfireImageName: perceptor-skyfire

  perceptorImageVersion: 2.0.3
  scannerImageVersion: 2.0.3
  perceiverImageVersion: 2.0.3
  imageFacadeImageVersion: 2.0.3
  skyfireImageVersion: 2.0.3

  imagePerceiver: false
  podPerceiver: true
  metrics: true
  perceptorSkyfire: false

  # CPU and memory configurations
  // Should be passed like: e.g. "300m"
  defaultCpu: 300m
  // Should be passed like: e.g "1300Mi"
  defaultMem: 1300Mi

  # Log level
  logLevel: debug

  # Environment Variables
  hubuserPasswordEnvVar: PCP_HUBUSERPASSWORD

  # Configuration secret
  secretName: opssight-secret
