apiVersion: v1
kind: Pod
metadata:
  name: protoform
spec:
  volumes:
  - name: viper-input
    configMap:
      name: viper-input
  containers:
  - name: protoform
    image: gcr.io/gke-verification/blackducksoftware/perceptor-protoform:master
    imagePullPolicy: Always
    command: [ ./protoform ]
    ports:
    - containerPort: 3001
      protocol: TCP
    volumeMounts:
    - name: viper-input
      mountPath: /etc/protoform/
  restartPolicy: Never
  serviceAccountName: protoform
  serviceAccount: protoform
---
apiVersion: v1
kind: List
metadata:
  name: viper-input
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: viper-input
  data:
    protoform.yaml: |
      DockerPasswordOrToken: "master"
      HubHost: ""
      HubUser: "sysadmin"
      HubPort: "8443"
      # TODO, inject as secret.
      HubUserPassword: ""
      ConcurrentScanLimit: "7"
      DockerUsername: "admin"
      Namespace: "hub"
      Openshift: "false"
      Registry: ""
      ImagePath: ""

      # TODO: Assuming for now that we run the same version of everything
      # For the curated installers.  For developers ? You might want to
      # hard code one of these values if using this script for dev/test.
      PerceptorContainerVersion: "master"
      ScannerContainerVersion: "master"
      PerceiverContainerVersion: "master"
      ImageFacadeContainerVersion: "master"
