apiVersion: synopsys.com/v1
kind: OpsSight
metadata:
  clusterName: ""
  name: opssight-test
spec:
  namespace: opssight-test
  # CONTAINER CONFIGS
  # These are sed replaced into the config maps for the containers.
  perceptorPort: 3001
  perceiverPort: 3002
  scannerPort: 3003
  imageFacadePort: 3004
  skyfirePort: 3005
  internalRegistries: []
  annotationIntervalSeconds: 30
  dumpIntervalMinutes: 30
  hubUser: sysadmin
  hubPort: 443
  hubUserPassword: blackduck
  hubClientTimeoutPerceptorMilliseconds: 100000
  hubClientTimeoutScannerSeconds: 600
  concurrentScanLimit: 2
  totalScanLimit: 1000
  checkForStalledScansPauseHours: 999999
  stalledScanClientTimeoutHours: 999999
  modelMetricsPauseSeconds: 15
  unknownImagePauseMilliseconds: 15000

  # CONTAINER PULL CONFIG
  # These are for defining docker registry and image location and versions
  registry: gcr.io
  imagePath: gke-verification/blackducksoftware
  # Default version will override the corresponding image version
  defaultVersion: ""

  perceptorImageName: perceptor
  scannerImageName: perceptor-scanner
  podPerceiverImageName: pod-perceiver
  imagePerceiverImageName: image-perceiver
  imageFacadeImageName: perceptor-imagefacade
  skyfireImageName: skyfire

  perceptorImageVersion: master
  scannerImageVersion: master
  perceiverImageVersion: master
  imageFacadeImageVersion: master
  skyfireImageVersion: master

  imagePerceiver: false
  podPerceiver: true
  metrics: true
  perceptorSkyfire: false

  # CPU and memory configurations
  # Should be passed like: e.g. "300m"
  defaultCpu: 300m
  # Should be passed like: e.g "1300Mi"
  defaultMem: 1300Mi

  # Log level
  logLevel: debug

  # Environment Variables
  hubuserPasswordEnvVar: PCP_HUBUSERPASSWORD

  # Configuration secret
  secretName: blackduck-secret
  useMockMode: false
