apiVersion: v1
kind: List
metadata:
  name: blackduck-protoform
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: blackduck-protoform
    labels:
      name: blackduck-protoform
  spec:
    replicas: 1
    selector:
      name: blackduck-protoform
    template:
      metadata:
        labels:
          name: blackduck-protoform
      spec:
        containers:
        - name: blackduck-protoform
          image: msenmurugan/protoform-installer:${BRANCHNAME}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
          - name: REGISTRATION_KEY
            value: ${REGISTRATION_KEY}
          volumeMounts:
          - mountPath: /etc/blackduck-protoform
            name: blackduck-protoform
          args:
          - /etc/blackduck-protoform/config.json
          command:
          - ./operator
        volumes:
        - configMap:
            defaultMode: 420
            name: blackduck-protoform
          name: blackduck-protoform
        serviceAccount: blackduck-protoform
- apiVersion: v1
  kind: Service
  metadata:
    name: blackduck-protoform
  spec:
    selector:
      name: blackduck-protoform
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
        name: blackduck-protoform
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: blackduck-protoform
  data:
    config.json: '{"DryRun": false, "LogLevel": "debug", "Namespace": "${NAMESPACE}", "Threadiness": 5, "PostgresRestartInMins": 10, "NFSPath" : "/kubenfs", "HubFederatorConfig": {"HubConfig": {"User": "sysadmin", "PasswordEnvVar": "HUB_PASSWORD", "ClientTimeoutMilliseconds": 5000, "Port": 443, "FetchAllProjectsPauseSeconds": 60}, "UseMockMode": false, "Port": 3016, "Registry": "gcr.io", "ImagePath": "saas-hub-stg/blackducksoftware", "ImageName": "federator", "ImageVersion": "master"}}'
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: blackduck-protoform
    namespace: ${NAMESPACE}
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: protoform-admin
  subjects:
  - kind: ServiceAccount
    name: blackduck-protoform
    namespace: ${NAMESPACE}
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: ""
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: 'true'
    labels:
      name: prometheus
    name: prometheus
  spec:
    selector:
      app: prometheus
    type: NodePort
    ports:
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: prometheus
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: prometheus
    template:
      metadata:
        name: prometheus
        labels:
          app: prometheus
      spec:
        containers:
        - name: prometheus
          image: prom/prometheus:v2.1.0
          args:
          - '--log.level=debug'
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/tmp/data/'
          ports:
          - name: web
            containerPort: 9090
          volumeMounts:
          - name: data
            mountPath: /data
          - name: config-volume
            mountPath: /etc/prometheus
        volumes:
        - name: data
          emptyDir: {}
        - name: config-volume
          configMap:
            name: prometheus
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: prometheus
  data:
    prometheus.yml: '{"global":{"scrape_interval":"5s"},"scrape_configs":[{"job_name":"blackduck-protoform-scrape","scrape_interval":"5s","static_configs":[{"targets":["blackduck-protoform:8080"]}]}]}'
